[project]
name = "mistralocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datauri>=1.0.0",
    "mistralai>=1.8.1",
    "python-dotenv>=1.1.0",
]

[project.scripts]
mistralocr = "main:main"
